name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup and validate environment
        run: |
          VALIDATION_MESSAGE="Everything worked, your environment is looking good"
          if ./setup_and_validate_environment.sh | grep -q "$VALIDATION_MESSAGE"; then
            echo "Validation succeeded: $VALIDATION_MESSAGE"
          else
            echo "Validation failed"
            exit 1
          fi

  clippy_check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

  build:
    runs-on: ubuntu-latest
    needs: clippy_check
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose